### ISSUE TITLE
OpenGL (GLSL): What may be the cause of the error “ERROR::SHADER::VERTEX::COMPILATION_FAILED”

### ISSUE THREAD

**Issue by ievn2015** [StanfordVL/iGibsonChallenge2021#2]
NVIDIA-SMI 430.50;       
Driver Version: 430.50;       
CUDA Version: 10.1;  
Ubuntu 16.04;    
4* GeForce RTX 2080 Ti Graphics Card;

It is OK when I follow the iGibson documents, Using Docker and remote GUI access via VNC http://svl.stanford.edu/igibson/docs/quickstart.html#using-docker-and-remote-gui-access-via-vnc
On my local machine, I can use any VNC client to visit the remote GUI.

However, when I go to the starter code for iGibsonChallenge2021, 
and 
run ./test_minival_locally.sh --docker-name my_submission

There is errors as follows:

./test_minival_locally.sh --docker-name my_submission
INFO:root:Importing iGibson (gibson2 module)
INFO:root:Assets path: /opt/iGibson/gibson2/data/assets
INFO:root:Gibson Dataset path: /opt/iGibson/gibson2/data/g_dataset
INFO:root:iG Dataset path: /opt/iGibson/gibson2/data/ig_dataset
INFO:root:3D-FRONT Dataset path: /opt/iGibson/gibson2/data/threedfront_dataset
INFO:root:CubiCasa5K Dataset path: /opt/iGibson/gibson2/data/cubicasa_dataset
INFO:root:Example path: /opt/iGibson/gibson2/examples
INFO:root:Example config path: /opt/iGibson/gibson2/examples/configs
pybullet build time: Dec 23 2020 01:46:51
ERROR::SHADER::VERTEX::COMPILATION_FAILED
0:1(10): error: GLSL 4.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

ERROR::SHADER::FRAGMENT::COMPILATION_FAILED
0:1(10): error: GLSL 4.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

ERROR::SHADER::PROGRAM::LINKING_FAILED
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
ERROR::SHADER::VERTEX::COMPILATION_FAILED
0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

ERROR::SHADER::FRAGMENT::COMPILATION_FAILED
0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

ERROR::SHADER::PROGRAM::LINKING_FAILED
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
torch is not available, falling back to rendering to memory(instead of tensor)
Compiling GLSL shader: /opt/iGibson/gibson2/render/mesh_renderer/shaders/450/equirect2cube_cs.glsl
Traceback (most recent call last):
  File "agent.py", line 34, in <module>
    main()
  File "agent.py", line 30, in main
    challenge.submit(agent)
  File "/opt/iGibson/gibson2/challenge/challenge.py", line 49, in submit
    physics_timestep=1.0 / 40.0)
  File "/opt/iGibson/gibson2/envs/igibson_env.py", line 57, in __init__
    render_to_tensor=render_to_tensor)
  File "/opt/iGibson/gibson2/envs/env_base.py", line 77, in __init__
    rendering_settings=settings)
  File "/opt/iGibson/gibson2/simulator.py", line 86, in __init__
    self.load()
  File "/opt/iGibson/gibson2/simulator.py", line 131, in load
    rendering_settings=self.rendering_settings)
  File "/opt/iGibson/gibson2/render/mesh_renderer/mesh_renderer_cpu.py", line 208, in __init__
    self.setup_pbr()
  File "/opt/iGibson/gibson2/render/mesh_renderer/mesh_renderer_cpu.py", line 224, in setup_pbr
    self.rendering_settings.light_dimming_factor
RuntimeError: Shader compilation failed: /opt/iGibson/gibson2/render/mesh_renderer/shaders/450/equirect2cube_cs.glsl
0:1(10): error: GLSL 4.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
0:0(0): error: Compute shaders require GLSL 4.30 or GLSL ES 3.10

**Comment by ChengshuLi** [comment]
Hi! Could you show me the output of
```
glxinfo | grep "OpenGL version"
```
?
Thanks!

**Comment by ievn2015** [comment]
Thank you for your kindly reply.
The output is
`OpenGL version string: 3.0 Mesa 18.0.5`

So It means that I need to upgrade my openGL version?

**Comment by fxia22** [comment]
looks like it is using mesa (software rendering) instead of using Nvidia GPU accelerated rendering.

**Comment by ChengshuLi** [comment]
Right, the output should be something like this
```
>>> glxinfo | grep "OpenGL version"
OpenGL version string: 4.6.0 NVIDIA 418.56
```

I don't have a definite answer because I wasn't able to reproduce your issue, but here are a few things you can try

1. Could you share the output of `ldconfig -p | grep EGL`?
2. Could you share the output of `nvidia-smi`?
3. Try `export LD_LIBRARY_PATH=/usr/lib/nvidia-<vvv>:$LD_LIBRARY_PATH`?
4. Try to make sure $DISPLAY variable is unset.

Can you try if any of the above solutions work?

**Comment by ievn2015** [comment]
thank you for your kindly reply，
I tried to use Nvidia GPU accelerated rendering， but failed.
1. The output of `ldconfig -p | grep EGL`

`libEGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so.1
libEGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL.so
libEGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so`

2. The output of `nvidia-smi`
`nvidia-smi
Wed Mar 31 13:00:13 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:03:00.0  On |                  N/A |
|  0%   27C    P8     1W / 250W |    132MiB / 11018MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:04:00.0 Off |                  N/A |
|  0%   27C    P8    10W / 250W |      1MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:81:00.0 Off |                  N/A |
|  0%   27C    P8     4W / 250W |      1MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
|  0%   27C    P8    12W / 250W |      1MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1692      G   /usr/lib/xorg/Xorg                           130MiB 
`

3. Tried `export LD_LIBRARY_PATH=/usr/lib/nvidia-<vvv>:$LD_LIBRARY_PATH`, but can not help;

4. Double checked  $DISPLAY variable is unset

Anyway, I will try to fix it, since you were not able to reproduce my issue.
Thank you again for your help!

**Comment by ievn2015** [comment]
I fixed it by reinstalling openGL.
Thanks for your help!

**Comment by ChengshuLi** [comment]
@ievn2015 Could you please describe the detailed steps you performed to reinstall openGL? Which commands did you run? I think your answer might help other people as well. Thank you.

**Comment by fxia22** [comment]
reopened for more visibility.

**Comment by ievn2015** [comment]
I think the problem was caused by my incomplete driver of openGL or NVIDIA.
I uninstalled the driver of NVIDIA, and deleted all the files of NVIDIA.
Then reboot, installed the driver of NVIDIA. OpenGL was installed automatically.
Now it works fine.

**Comment by arthur801031** [comment]
Here is what I did to get Nvidia driver showing up on `glxinfo | grep "OpenGL version"`:

1. Installed Nvidia Driver with OpenGL support: https://developer.nvidia.com/opengl-driver
2. Installed `sudo apt install mesa-utils`. I know this step is very counterintuitive since we don't want Mesa version showing up when we call `glxinfo`. However, without installing `mesa-utils`, you'll get `Command 'glxinfo' not found`. Therefore, it's essential that you install `mesa-utils` to get `glxinfo` to work. 

After these two steps, you'll get something similar to this:
```
OpenGL version string: 4.6.0 NVIDIA 470.63.01
```
